### PR TITLE
Fix Copyright + Authors

### PR DESCRIPTION
**Pull request by tmtmtmtm**
Part of https://github.com/everypolitician/everypolitician/issues/528

### CODE REVIEW

**Comment by tmtmtmtm** [comment]
@chrismytton @sagepe since we last updated this repo, it looks like gemrot has set in somewhere, and the tests no longer pass on travis, though they do for me locally. 

It looks like `file[:raw_url]` is now empty (where file is one of the files in a pull-request, returned from `octokit`, though this isn't a live request, but one recorded into `test/fixtures/vcr_cassettes/everypolitician-data-pr-16983.yml`), but none of my attempts to pin specific versions of `vcr`, `octokit`, or `sawyer` have helped. Any suggestions ?

I'm also not entirely sure that jumping to bundler 2.0 is the right move here, as I know there are some issues with that (e.g. heroku doesn't play well with it yet), but I _think_ that's a distinct problem to the failing tests (i.e. with only the first trivial commit, there are both bundler errors and test errors). Feel free to suggest a different/better approach than 5a6f71b, though.

**Comment by sagepe** [comment]
Part of this has got to be to do with the fact that Bundler 2.0.x will now likely be the default when installing a Ruby (see https://docs.travis-ci.com/user/languages/ruby/#bundler-20) and the way this is interacting with the Travis environment.

My operational conservatism on such matters would suggest pinning to 1.x for now and allowing some of the undoubted issues with 2.x to wash out (2.0.1 is a good example of this already, and noting the remark above re. Heroku). We can then get things working with 2.x when we are more sure that any problems are solely down to us.

The second suggestion in the Travis docs linked above suggests a way of removing the newer version of bundler in `before_install`. Although the error it cites is slightly different, it might still be worth a try.

**Comment by sagepe** [comment]
@tmtmtmtm - see #27, is this approach helpful?

**Comment by tmtmtmtm** [comment]
superseded by #27

**Pull request closed without merging**
